# Introduction {#sec:introduction}

Fishery-independent research surveys using longline trap gear have been conducted along British Columbia's (B.C) continental shelf by the Department of Fisheries and Oceans (DFO) in collaboration with the Canadian Sablefish Association (CSA) since 1988.  Developments in survey practices have advanced over the years with 1. standardized fishing sets (1988 - 2010) and traditional tagging sets (1991 - 2007) conducted at offshore indexing localities; 2. traditional tagging sets conducted at offshore tagging localities (1995 - 2008); 3. standardized fishing sets conducted at mainland inlet localities (1994 - 2019, 2021, 2022); and 4. stratified random sets conducted within five spatial strata (2003-2022).  

Since 2003, the stratified random survey has been used to collect catch and effort data, gather quantitative biological samples, capture oceanographic measurements, record video imagery of gear bottom contact (2013-2017, 2021, 2022) and acquire tag release and recapture data.  These data provide a fishery-independent source for assessing the biological status of the Sablefish stock and evaluating the fisheries management tools of the coastal Management Strategy Evaluation [@Johnson2023].  In 2021 and 2022, the Canadian Sablefish Association supported a benthic contact study with camera equipment to understand and quantify movement of longline trap gear.

  
\clearpage


